### ISSUE TITLE
Uname darwin

### ISSUE THREAD

**Issue by mrsnax** [m13253/dns-over-https#114] opened 2021-08-08 11:27 UTC
Hi

I tried to install **dns-over-https** with command **make**, and  I got stuck on uname darwin. Here's my results below : 

```
root@vps:~/dns-over-https-2.2.5# make
go get -d -u -v github.com/m13253/dns-over-https/doh-client/config
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/BurntSushi/toml v0.4.1
go get: upgraded github.com/BurntSushi/toml v0.3.1 => v0.4.1
go get -d -u -v github.com/m13253/dns-over-https/json-dns
go: downloading github.com/infobloxopen/go-trees v0.0.0-20200715205103-96a057b8dfb9
go: downloading github.com/miekg/dns v1.1.41
go: downloading github.com/miekg/dns v1.1.43
go: downloading golang.org/x/net v0.0.0-20210324205630-d1beb07c2056
go: downloading golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d
go: downloading golang.org/x/sys v0.0.0-20210324051608-47abb6519492
go: downloading golang.org/x/sys v0.0.0-20210806184541-e5e7981a1069
go get: upgraded github.com/miekg/dns v1.1.41 => v1.1.43
go get: upgraded golang.org/x/net v0.0.0-20210324205630-d1beb07c2056 => v0.0.0-20210805182204-aaa1db679c0d
go get: upgraded golang.org/x/sys v0.0.0-20210324051608-47abb6519492 => v0.0.0-20210806184541-e5e7981a1069
go get -d -v ./doh-client ./doh-server
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading golang.org/x/text v0.3.6
cd doh-client && go build
cd doh-server && go build
if [ "`uname`" = "Darwin" ]; then \
	make -C darwin-wrapper; \
fi
```

My VPS is ubuntu 18.04 and installed the latest Go.

How can I do?

Thanks

**Comment by m13253** [comment] 2021-08-08 11:30
Sorry but would you please reformat the log using three backticks?

**Comment by mrsnax** [comment] 2021-08-08 11:36
Done edited

**Comment by mrsnax** [comment] 2021-08-08 13:20
UPDATE

after trying again reinstall go now I got a error : 

```
Makefile:61: recipe for target 'deps' failed
make: *** [deps] Error 1
```


Any solution ? Thanks

**Comment by m13253** [comment] 2021-08-08 13:25
This is a strange problem, and it seems that the cause is not at my part.

There might be some issue with your system: does it have enough memory and disk space? Have you tried to restart the system?

**Comment by mrsnax** [comment] 2021-08-08 13:36
@m13253 

My systems specs are 

- 3GB RAM
- 2 Core CPU
- 40GB HDD space

![image](https://user-images.githubusercontent.com/6369589/128633829-7d76858a-6a66-4da9-89bf-d253f67784c7.png)

**Comment by m13253** [comment] 2021-08-08 13:48
This is very strange.
Have you tried to manually type the build command?
```
cd doh-client
go build
cd ..

cd doh-server
go build
cd ..
```
The program will be built to `doh-client/doh-client` and `doh-server/doh-server`.

**Comment by mrsnax** [comment] 2021-08-08 22:21
> This is very strange.
> Have you tried to manually type the build command?
> 
> ```
> cd doh-client
> go build
> cd ..
> 
> cd doh-server
> go build
> cd ..
> ```
> 
> The program will be built to `doh-client/doh-client` and `doh-server/doh-server`.

Hi, 

I try to `doh-server `and execute `go build` : 

```
root@vps:~/dns-over-https-2.2.5/doh-server# go build
google.go:27:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/root/go/src/context (from $GOPATH)
config.go:30:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/lib/go-1.6/src/github.com/BurntSushi/toml (from $GOROOT)
	/root/go/src/github.com/BurntSushi/toml (from $GOPATH)
server.go:40:2: cannot find package "github.com/gorilla/handlers" in any of:
	/usr/lib/go-1.6/src/github.com/gorilla/handlers (from $GOROOT)
	/root/go/src/github.com/gorilla/handlers (from $GOPATH)
google.go:37:2: cannot find package "github.com/m13253/dns-over-https/json-dns" in any of:
	/usr/lib/go-1.6/src/github.com/m13253/dns-over-https/json-dns (from $GOROOT)
	/root/go/src/github.com/m13253/dns-over-https/json-dns (from $GOPATH)
google.go:38:2: cannot find package "github.com/miekg/dns" in any of:
	/usr/lib/go-1.6/src/github.com/miekg/dns (from $GOROOT)
	/root/go/src/github.com/miekg/dns (from $GOPATH)
google.go:39:2: cannot find package "golang.org/x/net/idna" in any of:
	/usr/lib/go-1.6/src/golang.org/x/net/idna (from $GOROOT)
	/root/go/src/golang.org/x/net/idna (from $GOPATH)
```

and trying to execute `go build` inside `doh-client` folder  : 


```
client.go:27:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/root/go/src/context (from $GOPATH)
client.go:41:2: cannot find package "github.com/m13253/dns-over-https/doh-client/config" in any of:
	/usr/lib/go-1.6/src/github.com/m13253/dns-over-https/doh-client/config (from $GOROOT)
	/root/go/src/github.com/m13253/dns-over-https/doh-client/config (from $GOPATH)
client.go:42:2: cannot find package "github.com/m13253/dns-over-https/doh-client/selector" in any of:
	/usr/lib/go-1.6/src/github.com/m13253/dns-over-https/doh-client/selector (from $GOROOT)
	/root/go/src/github.com/m13253/dns-over-https/doh-client/selector (from $GOPATH)
client.go:43:2: cannot find package "github.com/m13253/dns-over-https/json-dns" in any of:
	/usr/lib/go-1.6/src/github.com/m13253/dns-over-https/json-dns (from $GOROOT)
	/root/go/src/github.com/m13253/dns-over-https/json-dns (from $GOPATH)
client.go:44:2: cannot find package "github.com/miekg/dns" in any of:
	/usr/lib/go-1.6/src/github.com/miekg/dns (from $GOROOT)
	/root/go/src/github.com/miekg/dns (from $GOPATH)
client.go:45:2: cannot find package "golang.org/x/net/http2" in any of:
	/usr/lib/go-1.6/src/golang.org/x/net/http2 (from $GOROOT)
	/root/go/src/golang.org/x/net/http2 (from $GOPATH)
client.go:46:2: cannot find package "golang.org/x/net/idna" in any of:
	/usr/lib/go-1.6/src/golang.org/x/net/idna (from $GOROOT)
	/root/go/src/golang.org/x/net/idna (from $GOPATH)
```

I've tried to execute `go clean` still nothing work

**Comment by m13253** [comment] 2021-08-09 14:35
I see the reason: You are using Go 1.6 (released in 2016).

I would suggest you to upgrade Go 1.16 first. Pay attention if you installed `golang-1.16` package through apt, the binaries might be installed into `/usr/lib/go-1.16/bin` instead of `/usr/bin`.

Another method is just to compile the code on your PC. Set environment variables `GOOS=linux`, `GOARCH=amd64`, `CGO_ENABLED=0` will allow you to cross-compile a Linux version even on Windows.

Personally I would also suggest you to upgrade to Ubuntu 20.04 (which has security updates until 2030) or Ubuntu 21.04 (which has security updates until 2022). But this depends on whether all your applications can support newer versions of OS.

**Comment by captainhook** [comment] 2021-09-13 19:52
I have tried with Go 1.16 and get the following error:

```
cow@pi1:~/dns-over-https$ go version
go version go1.16 linux/amd64
cow@pi1:~/dns-over-https$ which go
/usr/local/go/bin/go
cow@pi1:~/dns-over-https$ $GOROOT
-bash: /usr/local/go/: Is a directory
cow@pi1:~/dns-over-https$ $GOPATH
-bash: /home/cow/go: Is a directory
cow@pi1:~/dns-over-https$ make
cd doh-client && /usr/local/go//bin/go build
client.go:41:2: cannot find package "github.com/m13253/dns-over-https/v2/doh-client/config" in any of:
        /usr/local/go/src/github.com/m13253/dns-over-https/v2/doh-client/config (from $GOROOT)
        /home/cow/go/src/github.com/m13253/dns-over-https/v2/doh-client/config (from $GOPATH)
client.go:42:2: cannot find package "github.com/m13253/dns-over-https/v2/doh-client/selector" in any of:
        /usr/local/go/src/github.com/m13253/dns-over-https/v2/doh-client/selector (from $GOROOT)
        /home/cow/go/src/github.com/m13253/dns-over-https/v2/doh-client/selector (from $GOPATH)
client.go:43:2: cannot find package "github.com/m13253/dns-over-https/v2/json-dns" in any of:
        /usr/local/go/src/github.com/m13253/dns-over-https/v2/json-dns (from $GOROOT)
        /home/cow/go/src/github.com/m13253/dns-over-https/v2/json-dns (from $GOPATH)
client.go:44:2: cannot find package "github.com/miekg/dns" in any of:
        /usr/local/go/src/github.com/miekg/dns (from $GOROOT)
        /home/cow/go/src/github.com/miekg/dns (from $GOPATH)
client.go:45:2: cannot find package "golang.org/x/net/http2" in any of:
        /usr/local/go/src/golang.org/x/net/http2 (from $GOROOT)
        /home/cow/go/src/golang.org/x/net/http2 (from $GOPATH)
client.go:46:2: cannot find package "golang.org/x/net/idna" in any of:
        /usr/local/go/src/golang.org/x/net/idna (from $GOROOT)
        /home/cow/go/src/golang.org/x/net/idna (from $GOPATH)
Makefile:57: recipe for target 'doh-client/doh-client' failed
make: *** [doh-client/doh-client] Error 1
```

I hate to ask with such an error but I've exhausted my search... any tips?

**Comment by m13253** [comment] 2021-09-14 16:54
> I hate to ask with such an error but I've exhausted my search... any tips?

Try Go 1.17 first?

**Closed** 2022-09-03 08:44 UTC
