### ISSUE TITLE
new issue for random mode

### ISSUE THREAD

**Issue by small-sunshines** [m13253/dns-over-https#40] opened 2019-03-23 15:53 UTC
I am using this program. But I think I found a bug. It seems to be a bug related to a random query patched in version 2.0.0.

bug log:
```
172.19.0.240:54867 - - [23/Mar/2019:15:43:31 +0000] "BLUR FOR DOMAIN. IN TXT"
panic: invalid argument to Intn
goroutine 22 [running]:
math/rand.(*Rand).Intn(0xc00008a180, 0x0, 0x13)
	/usr/local/go/src/math/rand/rand.go:169 +0x9c math/rand.Intn(...)
	/usr/local/go/src/math/rand/rand.go:329 github.com/m13253/dns-over-https/doh-client/selector.(*RandomSelector).Get(0xc0000931e0, 0xc00009cc20)
	/tmp/dns-over-https-2.0.0/doh-client/selector/randomSelector.go:45 +0x3f main.(*Client).handlerFunc(0xc0000955f0, 0x85b660, 0xc0000a05a0, 0xc0000fa090, 0xc00004be00)
	/tmp/dns-over-https-2.0.0/doh-client/client.go:365 +0x322 main.(*Client).udpHandlerFunc(...)
	/tmp/dns-over-https-2.0.0/doh-client/client.go:443 github.com/miekg/dns.HandlerFunc.ServeDNS(0xc000114490, 0x85b660, 0xc0000a05a0, 0xc0000fa090)
	/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:37 +0x44 github.com/miekg/dns.(*Server).serveDNS(0xc000112500, 0xc000142000, 0x36, 0x1000, 0xc0000a05a0)
	/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:603 +0x2b8 github.com/miekg/dns.(*Server).serveUDPPacket(0xc000112500, 0xc000028020, 0xc000142000, 0x36, 0x1000, 0xc000010010, 0xc000093280)
	/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:549 +0xb2 created by github.com/miekg/dns.(*Server).serveUDP
	/go/pkg/mod/github.com/miekg/dns@v1.1.6/server.go:479 +0x27a
```

I will wait for a quick reply.

**Comment by m13253** [comment] 2019-03-23 16:32
Would you please paste your configuration file? (You can censor your privacy info)

By the way, CC @Sherlock-Holo .

**Comment by small-sunshines** [comment] 2019-03-23 17:56
```conf
# DNS listen port
listen = [
    "0.0.0.0:5380"
]

# HTTP path for upstream resolver

[upstream]

# available selector: random or weighted_round_robin or lvs_weighted_round_robin
upstream_selector = "weighted_round_robin"

# weight should in (0, 100], if upstream_selector is random, weight will be ignored

## Google's productive resolver, good ECS, bad DNSSEC
#[[upstream.upstream_google]]
#    url = "https://dns.google.com/resolve"
#    weight = 50

## CloudFlare's resolver, bad ECS, good DNSSEC
#[[upstream.upstream_google]]
#    url = "https://cloudflare-dns.com/dns-query"
#    weight = 50

## CloudFlare's resolver, bad ECS, good DNSSEC
#[[upstream.upstream_google]]
#    url = "https://1.1.1.1/dns-query"
#    weight = 50

# CloudFlare's resolver, bad ECS, good DNSSEC
[[upstream.upstream_ietf]]
    url = "https://cloudflare-dns.com/dns-query"
    weight = 50

## CloudFlare's resolver, bad ECS, good DNSSEC
#[[upstream.upstream_ietf]]
#    url = "https://1.1.1.1/dns-query"
#    weight = 50

## Google's experimental resolver, good ECS, good DNSSEC
#[[upstream.upstream_ietf]]
#    url = "https://dns.google.com/experimental"
#    weight = 50

## CloudFlare's resolver for Tor, available only with Tor
## Remember to disable ECS below when using Tor!
## Blog: https://blog.cloudflare.com/welcome-hidden-resolver/
#[[upstream.upstream_ietf]]
#    url = "https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query"
#    weight = 50


[others]
# Bootstrap DNS server to resolve the address of the upstream resolver
# If multiple servers are specified, a random one will be chosen each time.
# If empty, use the system DNS settings.
# If you want to preload IP addresses in /etc/hosts instead of using a
# bootstrap server, please make this list empty.
bootstrap = [

    # Google's resolver, bad ECS, good DNSSEC
    "8.8.8.8:53",
    "8.8.4.4:53",

    # CloudFlare's resolver, bad ECS, good DNSSEC
    #"1.1.1.1:53",
    #"1.0.0.1:53",

]

# The domain names here are directly passed to bootstrap servers listed above,
# allowing captive portal detection and systems without RTC to work.
# Only effective if at least one bootstrap server is configured.
passthrough = [
    "captive.apple.com",
    "connectivitycheck.gstatic.com",
    "detectportal.firefox.com",
    "msftconnecttest.com",
    "nmcheck.gnome.org",

    "pool.ntp.org",
    "time.apple.com",
    "time.asia.apple.com",
    "time.euro.apple.com",
    "time.nist.gov",
    "time.windows.com",
]

# Timeout for upstream request in seconds
timeout = 30

# Disable HTTP Cookies
#
# Cookies may be useful if your upstream resolver is protected by some
# anti-DDoS services to identify clients.
# Note that DNS Cookies (an DNS protocol extension to DNS) also has the ability
# to track uesrs and is not controlled by doh-client.
no_cookies = true

# Disable EDNS0-Client-Subnet (ECS)
#
# DNS-over-HTTPS supports EDNS0-Client-Subnet protocol, which submits part of
# the client's IP address (/24 for IPv4, /56 for IPv6 by default) to the
# upstream server. This is useful for GeoDNS and CDNs to work, and is exactly
# the same configuration as most public DNS servers.
no_ecs = false

# Disable IPv6 when querying upstream
#
# Only enable this if you really have trouble connecting.
# Doh-client uses both IPv4 and IPv6 by default and should not have problems
# with an IPv4-only environment.
# Note that DNS listening and bootstrapping is not controlled by this option.
no_ipv6 = false

# Enable logging
verbose = true

**Comment by Sherlock-Holo** [comment] 2019-03-24 01:00
I think I know what happened, it should be `rand.Intn(len(rs.upstreams))` instead of `rand.Intn(len(rs.upstreams)-1)`
by the way, the config you posted doesn't use random mode, when you found this bug, did you use `weighted_round_robin` mode? It should use another selector not random selector

**Comment by Sherlock-Holo** [comment] 2019-03-24 01:08
PR is created

**Comment by m13253** [comment] 2019-03-24 01:13
Merged PR #41 
Please report if the problem is fixed.

**Comment by felipe19930** [comment] 2019-03-24 03:04
I'm not the author but I was experiencing the exact same error using the `random` selector. 

PR #41 fixed it for me. Can you retag the 2.0.0 release to the working version? Thanks!

**Comment by small-sunshines** [comment] 2019-03-24 04:01
@Sherlock-Holo I also got an error when using random selection. However, in the configuration, I forgot that I had already changed to another setting and just uploaded it.

**Comment by m13253** [comment] 2019-03-24 11:11
> PR #41 fixed it for me. Can you re-tag the 2.0.0 release to the working version, or make a new one?

Tagged 2.0.1

**Closed** 2019-03-24 11:11 UTC
