### ISSUE TITLE
[Feature request] primary server and backup server

### ISSUE THREAD

**Issue by Gontier-Julien** [m13253/dns-over-https#138] opened 2022-09-14 22:23 UTC
It would be nice to have an option on the upstream DNS server selection, to have a primary server and others servers setup as backup in case the primary one fail ^^

It would be useful instead of doing a setup like:

Doh server ==> nginx load balance ==> local (or non-local) DNS server 

So kinda something like this:

Doh server ==> if primary DNS server available then use it, if it down go to the backup one

**Comment by m13253** [comment] 2022-09-19 01:03
Duplicate of #100.
Mainly delayed due to lack of development resource.
PRs are welcome.

**Closed by m13253** 2022-09-19 01:03 UTC
