### ISSUE TITLE
doh-server data race 

### ISSUE THREAD

**Issue by bejaneps** [m13253/dns-over-https#87] opened 2020-08-28 18:11 UTC
# Minimal issue reproduction

**Go version**

1.15

**OS and Architecture**

Ubuntu/Bionic Beaver - amd64

**Steps**

Run following test with _-race_ flag on doh-server/server.go file. I've created a server_test.go file inside doh-server folder, copying here just a part of test that outputs data race and fails. Command
```go
// loadWebsitesFromCSV loads and returns list of 1000 websites from .csv file (used for high load testing)
func loadWebsitesFromCSV() ([]string, error) {
	f, err := os.Open("websites.csv")
	if err != nil {
		return nil, errors.Wrap(err, "failed to load websites csv")
	}
	defer f.Close()

	csvR := csv.NewReader(f)
	var websites []string
	for {
		rec, err := csvR.Read()
		if err == io.EOF {
			break
		} else if err != nil {
			return nil, errors.Wrap(err, "failed to read record from websites csv")
		}

		websites = append(websites, rec[1]) // 1 index is website's name
	}

	return websites, nil
}

// worker sends a request to dns server
func worker(errChan chan<- error, websiteChan <-chan string, wg *sync.WaitGroup) {
	defer wg.Done()
	for {
		// check if websites are finished
		w, ok := <-websiteChan
		if !ok {
			return
		}

		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()

		// prapare dns json request
		reqURL := fmt.Sprintf("http://127.0.0.1:8053/dns-query?name=%s&type=1", w)
		req, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
		if err != nil {
			errChan <- errors.Errorf("website: %s, failed to create new GET request: %s", w, err)
			return
		}
		req.Close = true

		// add headers for google request
		req.Header.Add("Content-Type", "application/dns-json")
		req.Header.Add("Accept", "application/json")

		// send it to dns server
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			errChan <- errors.Errorf("website: %s, failed to make GET request: %s", w, err)
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode != 200 {
			errChan <- errors.Errorf("website: %s, expected 200 response status code, got: %d", w, resp.StatusCode)
		}
	}
}

// TestHTTPServerWithLoad performs high load test on HTTP DNS server using 1000 domains from .csv file.
//
// Command for testing: go test -race -v doh-server/*.go -run ^TestHTTPServerWithLoad$
func TestHTTPServerWithLoad(t *testing.T) {
	conf := prepareConfig()
	conf.Listen = []string{
		"127.0.0.1:8053",
		"[::1]:8053",
	}

	// initialize a new server
	srv, err := NewServer(conf)
	if err != nil {
		t.Fatalf("failed to initialize new server: %v", err)
	}

	// start a server
	srvErr := make(chan error)
	go func(srvErr chan<- error) {
		if err := srv.Start(); err != nil {
			srvErr <- err
			return
		}
	}(srvErr)

	select {
	case <-srvErr:
		t.Fatalf("failed to start a server: %v", <-srvErr)
		break
	default:
		time.Sleep(500 * time.Millisecond) // sleep for some mills, so server has time to start

		// load 1000 websites from csv
		websites, err := loadWebsitesFromCSV()
		if err != nil {
			t.Fatal(err)
		}

		// run 11 workers, so requests would be faster
		websiteChan := make(chan string, 999)
		errChan := make(chan error, 10)
		wg := sync.WaitGroup{}
		for i := 0; i < 12; i++ {
			go worker(errChan, websiteChan, &wg)
			wg.Add(1)
		}

		// sends 1000 website to workers
		for _, w := range websites {
			websiteChan <- w
		}
		close(websiteChan)

		// if any error happens while sending request, just log it
		go func() {
			for err := range errChan {
				t.Log(err)
			}
			close(errChan)
		}()

		wg.Wait()
	}
}
```

**Output**

WARNING DATA RACE
github.com/miekg/dns.(*Client).ExchangeContext()
command-line-arguments.(*Server).doDNSQuery()
command-line-arguments.(*Server).handlerFunc()

Previous read at 0x00c00018ab80 by goroutine 31:
github.com/miekg/dns.(*Client).getTimeoutForRequest()
github.com/miekg/dns.(*Client).exchange()
github.com/miekg/dns.(*Client).ExchangeWithConn()
github.com/miekg/dns.(*Client).Exchange()
github.com/miekg/dns.(*Client).ExchangeContext()
command-line-arguments.(*Server).doDNSQuery()
command-line-arguments.(*Server).handlerFunc()

Goroutine 52 (running) created at:
net/http.(*Server).Serve()
net/http.(*Server).ListenAndServe()

Previous write at 0x00c000125620 by goroutine 62:
github.com/miekg/dns.(*Client).ExchangeContext()
command-line-arguments.(*Server).doDNSQuery()
command-line-arguments.(*Server).handlerFunc()

and so on ...

**Remarks**

I've changed private _config_ struct in server.go file to public in order to perform test. Link to [websites.csv](https://gist.github.com/bejaneps/ba8d8eed85b0c289a05c750b3d825f61) file. So, as I see there is data race specifically in doDnsQuery and ExchangeContext functions. I hope I'm not doing wrong tests.

**Comment by m13253** [comment] 2020-08-29 13:12
Thank you for your test. I think this is a serious problem.
However, according to the stack trace, the issue is located in miekg's DNS library.

I suggest you conduct a test upon that library and see whether it is a bug at that side.

**Comment by bejaneps** [comment] 2020-08-29 13:50
@m13253 Sorry for mistake, I was testing using go 1.15 not 1.5 :) 

I will test miekg dns library as well, and see if it's related to it.

Thanks for early reply.

**Comment by m13253** [comment] 2021-01-04 19:15
Closing because this is an issue of either outdated versions or third-party libraries.

**Closed by m13253** 2021-01-04 19:15 UTC
